version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
  api:
    build: api
    ports:
      - 5555:5000

  adminer:
    image: adminer
    ports:
      - 8888:8080